version: '3.8'

services:
  backend:
    build:
      context: ./api
    container_name: backend
    environment:
      - SQLALCHEMY_DATABASE_URL
    volumes:
      - ./uploads:/uploads
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./app
    container_name: frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
