from .client_repository import ClientRepository
from .car_repository import CarRepository
from .rental_repository import RentalRepository
from .price_repository import PriceRepository
from .invoice_repository import InvoiceRepository
from .invoice_element_repository import InvoiceElementRepository