from .brand_controller import router as brand_controller
from .car_controller import router as car_controller
from .client_controller import router as client_controller
from .invoice_controller import router as invoice_controller
from .model_controller import router as model_controller
from .price_controller import router as price_controller
from .rental_controller import router as rental_controller
from .report_controller import router as report_controller
from .segment_controller import router as segment_controller
